added cache tests for basic seqslice cache & NLMSASlice use; latter FAILS.
This is because of a memory leak present in the NLMSASlice
implementation. NLMSASlice.__dealloc__ tries to remove the cached ref
holder but fails (more or less silently) because pyrex __dealloc__
cannot call Python code.

This patch adds some error reporting code to cnestedlist.pyx, too;
the generated error is:

Traceback (most recent call last):
  File "pygr.cnestedlist.pyx", line 577, in pygr.cnestedlist.__dealloc__
TypeError: 'DummyProxyDict' object doesn't support item deletion
Exception exceptions.TypeError: TypeError("'DummyProxyDict' object
doesn't support item deletion",) in <pygr.cnestedlist.NLMSASlice
object at 0x8536a94> ignored

This is because __delitem__ cannot be called from Pyrex.